# -*- coding: utf-8 -*-
"""
Created on Mon Jun 15 20:15:28 2026

@author: nicho
"""

import pandas as pd
import os
import sys
import numpy as np
import time
from sklearn.model_selection import train_test_split as splitSet
from sklearn.neural_network import MLPRegressor
import scatter3d as s3d
import matplotlib.pyplot as plt
from sklearn.preprocessing import MaxAbsScaler as MAS

'''
This code is to generate 3D surfaces of predictions done by the neural network
in order to compare with equations generated by symbolic regression
'''

#energyList = [150,250,400,600,800,1000,1200]
energyList = ['xytrain90']
f1list = ['xsection','incompressability','f1','v2']

#create and move to designated folder
L = len(sys.argv)
if L > 1:
    if not(os.path.isdir(sys.argv[1])): #check if folder already exists
        os.makedirs(sys.argv[1])
    os.chdir(sys.argv[1])

#Create folder if needed
else:
    newDirectory = input(r"What new folder if any?: ")
    if not(os.path.isdir(newDirectory)): 
        os.makedirs(newDirectory)
    os.chdir(newDirectory)

#Start loop that cycles through beam energy list
for i in energyList:
    #import data before changing directories
    #names of data in xytrain90.dat
    columns = ['xsection','incompressability','f1n','v2n','f1','v2']
    #where the data file is
    datasetDirectory = fr"C:\Users\nicho\Downloads\Research\Dr. Li\DNN+Bayes\Traing data\{i}.dat"
    dataset = pd.read_csv(datasetDirectory, names = columns)
    #create tuples to hold the HADES experimental data and errors
    exp_data = (0.458, -0.06)
    exp_sigma = (0.03, 0.01)
    
    #Cycle through the list of possible datasets
    for data in f1list:
        if data == 'xsection':
            inputValues = dataset[['f1','v2']].to_numpy()
            f1Values = dataset[['xsection']].to_numpy()
            r2min = 0.99
            string1 = 'F1'
            string2 = 'v2'
            string3 = 'X'
            sigma = 0
            
        elif data == 'incompressability':
            inputValues = dataset[['f1','v2']].to_numpy()
            f1Values = dataset[['incompressability']].to_numpy()
            r2min = 0.99
            string1 = 'F1'
            string2 = 'v2'
            string3 = 'K'
            sigma = 0
        
        elif data == 'f1':
            inputValues = dataset[['xsection','incompressability']].to_numpy()
            f1Values = dataset[['f1']].to_numpy()
            r2min = 0.99
            string1 = 'X'
            string2 = 'K'
            string3 = 'F1'
            sigma = exp_sigma[0]
        
        elif data == 'v2':
            inputValues = dataset[['xsection','incompressability']].to_numpy()
            f1Values = dataset[['v2']].to_numpy()
            r2min = 0.99
            string1 = 'X'
            string2 = 'K'
            string3 = 'v2'
            sigma = exp_sigma[1]
        
        #copy original values for comparision
        inputValuesOrig = inputValues.copy()
        f1ValuesOrig = f1Values.copy().ravel()
        
        #use the Maximum Absolute Scaler from Scikit-Learn on the data
        inputScaler = MAS() #input and output use separate scalers
        f1Scaler = MAS()
        
        #Normalize input and output data
        inputValues = inputScaler.fit_transform(inputValues)
        f1Values = f1Scaler.fit_transform(f1Values)
        
        #try each beam energy and data type 5 times
        for trynum in range(5):
            #record start time
            totalStart = start = time.perf_counter()
            #send general output here
            outLog = open(f".\out{i}{data}{trynum}.log", "w")
            np.set_printoptions(suppress=True)
            #set up how things will be printed
            np.set_printoptions(suppress=True) #do not use scientific notation
            
            #store the seed scores in a file
            dnnDat = open(f"./dnnSeedScore{i}{data}{trynum}.dat", "w")
            
            #initialize model score, which is measured by R^2=1-SSE/TSS
            f1Score = 0
            v2Score = 0
            numModelTry = 0 #number of tries to get succesful model
            max_iter = 400 #Set maximum iteration number
            
            #Start a list to store scores
            scores = []
            #generate model for f1
            #set R^2=0.99 as minimum threshold of performance
            while f1Score < r2min:
                #generate random number as seeds for splitting and model initialization
                splitSeed = np.random.randint(0,2**31-1) #split everything consistently
                f1ModelSeed = np.random.randint(0,2**31-1) #models initialized different
            
                #Record seed scores
                print('split seed:', splitSeed, file = dnnDat)
                print('f1 model seed:', f1ModelSeed, file = dnnDat)
            
                #split the values 75% for training and 25% for testing
                inputTrain, inputTest, f1Train, f1Test = splitSet(
                        inputValues, f1Values, test_size = 0.25,
                        random_state = splitSeed)
            
                #train model
                f1Model = MLPRegressor(hidden_layer_sizes=(2,6,6,2),
                        activation = 'tanh', solver = 'lbfgs', max_iter = max_iter,
                        random_state = f1ModelSeed).fit(inputTrain, f1Train)
            
                #test model accuracy and record it, store score value
                f1Score = f1Model.score(inputTest, f1Test) #R^2=1-SSE/TSS
                print('f1 score:', f1Score, file = dnnDat)
                scores.append(f1Score)
            
                numModelTry += 1
            
                #if model try hits 1000, then decrease r2min to max r2 score in the list -0.05
                if f1Score < r2min and numModelTry == 1000:
                    r2min = max(scores) - 0.005
                    print("Minimum Test r2 changed to", r2min, file = outLog)
        
            #record score of the models
            print('model accepted after try:', numModelTry, file = outLog)
            print('f1 score', f1Score, file = outLog)
            
            #Record ending time
            endtrain1 = time.perf_counter() #record ending time
            print('time to complete first DNN training:', endtrain1 - start, file = outLog)
            
            #Close file
            start = time.perf_counter()
            dnnDat.close()
            
            #reshape f1 values
            f1Values = np.ravel(f1Values)
            
            #Set up grid values and make grid
            X, Y = s3d.makeGrid(inputValues[:,0], inputValues[:,1])
            gridPoints = np.column_stack((X.ravel(), Y.ravel()))
            
            #predict values for the grid
            Z = f1Model.predict(gridPoints)
            Z = f1Scaler.inverse_transform(Z.reshape(-1, 1)).reshape(X.shape)
            
            #predict values from input data
            zModel = f1Model.predict(inputValues)
            zModel = f1Scaler.inverse_transform(zModel.reshape(-1, 1)).ravel()
            
            #Print shapes for debugging
            print("inputValues:", inputValues.shape)
            print("f1Values:", f1Values.shape)
            print("zModel:", zModel.shape)
            print("Z:", Z.shape)
            
            #Set up file names
            filename = f"Dnn{string3}3Dtry{i}{data}{trynum}.pdf"
            filename2 = f"Dnn{string3}Error{i}{data}{trynum}.pdf"
            title = f"Dnn{string3}3D{i}{data}{trynum}"
            title2 = f"Dnn{string3}Error{i}{data}{trynum}"
            
            #find score of model and setup function parameter
            R22 = f1Model.score(inputValues, f1Values)
            function = ""
            
            #Set up graph axes and figure
            fig,ax = s3d.surf3d(inputValuesOrig[:,0],inputValuesOrig[:,1],f1ValuesOrig,zModel,
                                      Z,string1,string2,string3,proj=False,title = title, textstr = function, r2 = R22, sigma = sigma, guy = string3)
            fig.savefig(filename, format="pdf")
            plt.close(fig)
            
            #Set up error plots and save them
            fig,ax = s3d.plotErr(f1ValuesOrig,zModel,xlab=string3,title = title2,sigma = sigma)
            fig.savefig(filename2, format="pdf")
            plt.close(fig)
            
            #print scores
            print("Training R²:", f1Model.score(inputTrain, f1Train))
            print("Testing  R²:", f1Model.score(inputTest, f1Test))
            print("Overall  R²:", f1Model.score(inputValues, f1Values))
            
            #print ranges for debugging purposes
            print("f1 range:", np.min(f1Values), np.max(f1Values))
            print("pred range:", np.min(zModel), np.max(zModel))
            
            #Find time taken to graph and close files
            endtrain2 = time.perf_counter() #record ending time
            print('time to complete graphing:', endtrain2 - start, file = outLog)
            outLog.close()

#other experimental FOPI data
'''
    if i <= 200:
        #150MeV FOPI data
        exp_data = (0.279, -0.005)
        exp_sigma = (0.012, 0.005)
    elif ((i > 200) and (i <= 325)):
        #250MeV FOPI data
        exp_data = (0.373,-0.055)
        exp_sigma = (0.015,0.004)
    elif ((i > 325) and (i <= 500)):
        #400MeV FOPI data
        exp_data = (0.453, -.071)
        exp_sigma = (0.016, 0.005)
    elif ((i > 500) and (i <= 700)):
        #600MeV FOPI data
        exp_data = (0.498, -0.074)
        exp_sigma = (0.016, 0.004)
    elif ((i > 700) and (i <= 900)):
        #800MeV FOPI data
        exp_data= (0.516, -0.072)
        exp_sigma = (0.019, 0.005)
    elif ((i > 900) and (i <= 1100)):
        #1000MeV FOPI data
        exp_data = (0.518, -0.066)
        exp_sigma = (0.017, 0.005)
    elif ((i > 1100) and (i <= 1215)):
        #1200MeV FOPI data
        exp_data = (0.54, -0.058)
        exp_sigma = (0.019, 0.005)
        
    else:
'''